by: Victor Camero

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier 
from sklearn.tree import plot_tree

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/dalark/.local/lib/python3.13/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/home/dalark/.local/lib/python3.13/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/home/dalark/.local/lib/python3.13/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/home/dalark/.local/lib/python3.13/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib64/python3.13/asyncio/base_events.py", line 683, in run_forever
    self._run_once()
  File "/usr/lib64/python3.13/asyncio/base_events.py", line 2040, in _run_once
    handle._run()
  File "/usr/lib64/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/home/dalark/.local/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/home/dalark/.local/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/home/dalark/.local/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/home/dalark/.local/lib/python3.13/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/home/dalark/.local/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/home/dalark/.local/lib/python3.13/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/home/dalark/.local/lib/python3.13/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/home/dalark/.local/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "/home/dalark/.local/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "/home/dalark/.local/lib/python3.13/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/home/dalark/.local/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/home/dalark/.local/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/home/dalark/.local/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_38935/309431644.py", line 2, in <module>
    import pandas as pd
  File "/home/dalark/.local/lib/python3.13/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/home/dalark/.local/lib/python3.13/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/home/dalark/.local/lib/python3.13/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/home/dalark/.local/lib/python3.13/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/home/dalark/.local/lib/python3.13/site-packages/pandas/core/arrays/arrow/array.py", line 50, in <module>
    from pandas.core import (
  File "/home/dalark/.local/lib/python3.13/site-packages/pandas/core/ops/__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "/home/dalark/.local/lib/python3.13/site-packages/pandas/core/ops/array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "/home/dalark/.local/lib/python3.13/site-packages/pandas/core/computation/expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "/home/dalark/.local/lib/python3.13/site-packages/pandas/core/computation/check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "/home/dalark/.local/lib/python3.13/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/lib64/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib64/python3.13/site-packages/numexpr/__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.4 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

In [2]:
dataset_el_pino = pd.read_csv("../data/dataModelCSV/withingLastNumberGRD.csv", sep=";")
dataset_el_pino.head()

,Diag 01 Principal (cod+des),Diag 02 Secundario (cod+des),Diag 03 Secundario (cod+des),Diag 04 Secundario (cod+des),Diag 05 Secundario (cod+des),Diag 06 Secundario (cod+des),Diag 07 Secundario (cod+des),Diag 08 Secundario (cod+des),Diag 09 Secundario (cod+des),Diag 10 Secundario (cod+des),...,Proced 24 Secundario (cod+des),Proced 25 Secundario (cod+des),Proced 26 Secundario (cod+des),Proced 27 Secundario (cod+des),Proced 28 Secundario (cod+des),Proced 29 Secundario (cod+des),Proced 30 Secundario (cod+des),Edad en años,Sexo (Desc),GRD
0,A41.8,B37.6,I39.8,N10,B96.1,L89.9,L08.9,B96.2,A41.5,J86.9,...,99.84,88.72,90.42,90.52,91.39,91.33,87.03,40,1,18410
1,U07.1,J12.8,R06.0,R05,R50.9,Z29.0,Z01.7,J96.00,J94.2,J92.9,...,91.62,90.43,91.39,90.52,91.32,96.59,90.99,53,1,4101
2,K56.5,R57.2,R57.1,J80,Y95,J15.0,U82.2,B95.6,B96.8,B37.1,...,99.84,91.73,90.53,99.26,89.39,89.66,89.65,65,1,4101
3,K76.8,K66.1,N18.5,D64.9,E87.5,E87.2,J81,N17.8,J44.9,R41.0,...,57.94,0.13,0.17,99.04,99.18,99.21,99.23,61,1,4102
4,T81.0,Y83.2,S31.1,S36.80,W31.62,J96.09,J15.0,U82.2,U07.1,N39.0,...,90.52,91.39,91.32,93.90,99.15,96.59,45.13,30,1,4102

In [3]:
rows, columns = dataset_el_pino.shape

In [4]:
dataset_el_pino.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14279 entries, 0 to 14278
Data columns (total 68 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Diag 01 Principal (cod+des)     14279 non-null  object
 1   Diag 02 Secundario (cod+des)    14279 non-null  object
 2   Diag 03 Secundario (cod+des)    14279 non-null  object
 3   Diag 04 Secundario (cod+des)    14279 non-null  object
 4   Diag 05 Secundario (cod+des)    14279 non-null  object
 5   Diag 06 Secundario (cod+des)    14279 non-null  object
 6   Diag 07 Secundario (cod+des)    14279 non-null  object
 7   Diag 08 Secundario (cod+des)    14279 non-null  object
 8   Diag 09 Secundario (cod+des)    14279 non-null  object
 9   Diag 10 Secundario (cod+des)    14279 non-null  object
 10  Diag 11 Secundario (cod+des)    14279 non-null  object
 11  Diag 12 Secundario (cod+des)    14279 non-null  object
 12  Diag 13 Secundario (cod+des)    14279 non-null  object
 13  Diag 14 Secundario (cod+des)    14279 non-null  object
 14  Diag 15 Secundario (cod+des)    14279 non-null  object
 15  Diag 16 Secundario (cod+des)    14279 non-null  object
 16  Diag 17 Secundario (cod+des)    14279 non-null  object
 17  Diag 18 Secundario (cod+des)    14279 non-null  object
 18  Diag 19 Secundario (cod+des)    14279 non-null  object
 19  Diag 20 Secundario (cod+des)    14279 non-null  object
 20  Diag 21 Secundario (cod+des)    14279 non-null  object
 21  Diag 22 Secundario (cod+des)    14279 non-null  object
 22  Diag 23 Secundario (cod+des)    14279 non-null  object
 23  Diag 24 Secundario (cod+des)    14279 non-null  object
 24  Diag 25 Secundario (cod+des)    14279 non-null  object
 25  Diag 26 Secundario (cod+des)    14279 non-null  object
 26  Diag 27 Secundario (cod+des)    14279 non-null  object
 27  Diag 28 Secundario (cod+des)    14279 non-null  object
 28  Diag 29 Secundario (cod+des)    14279 non-null  object
 29  Diag 30 Secundario (cod+des)    14279 non-null  object
 30  Diag 31 Secundario (cod+des)    14279 non-null  object
 31  Diag 32 Secundario (cod+des)    14279 non-null  object
 32  Diag 33 Secundario (cod+des)    14279 non-null  object
 33  Diag 34 Secundario (cod+des)    14279 non-null  object
 34  Diag 35 Secundario (cod+des)    14279 non-null  object
 35  Proced 01 Principal (cod+des)   14279 non-null  float64
 36  Proced 02 Secundario (cod+des)  14279 non-null  float64
 37  Proced 03 Secundario (cod+des)  14279 non-null  float64
 38  Proced 04 Secundario (cod+des)  14279 non-null  float64
 39  Proced 05 Secundario (cod+des)  14279 non-null  float64
 40  Proced 06 Secundario (cod+des)  14279 non-null  float64
 41  Proced 07 Secundario (cod+des)  14279 non-null  float64
 42  Proced 08 Secundario (cod+des)  14279 non-null  float64
 43  Proced 09 Secundario (cod+des)  14279 non-null  float64
 44  Proced 10 Secundario (cod+des)  14279 non-null  float64
 45  Proced 11 Secundario (cod+des)  14279 non-null  float64
 46  Proced 12 Secundario (cod+des)  14279 non-null  float64
 47  Proced 13 Secundario (cod+des)  14279 non-null  float64
 48  Proced 14 Secundario (cod+des)  14279 non-null  float64
 49  Proced 15 Secundario (cod+des)  14279 non-null  float64
 50  Proced 16 Secundario (cod+des)  14279 non-null  float64
 51  Proced 17 Secundario (cod+des)  14279 non-null  float64
 52  Proced 18 Secundario (cod+des)  14279 non-null  float64
 53  Proced 19 Secundario (cod+des)  14279 non-null  float64
 54  Proced 20 Secundario (cod+des)  14279 non-null  float64
 55  Proced 21 Secundario (cod+des)  14279 non-null  float64
 56  Proced 22 Secundario (cod+des)  14279 non-null  float64
 57  Proced 23 Secundario (cod+des)  14279 non-null  float64
 58  Proced 24 Secundario (cod+des)  14279 non-null  float64
 59  Proced 25 Secundario (cod+des)  14279 non-null  float64
 60  Proced 26 Secundario (cod+des)  14279 non-null  float64
 61  Proced 27 Secundario (cod+des)  14279 non-null  float64
 62  Proced 28 Secundario (cod+des)  14279 non-null  float64
 63  Proced 29 Secundario (cod+des)  14279 non-null  float64
 64  Proced 30 Secundario (cod+des)  14279 non-null  float64
 65  Edad en años                    14279 non-null  int64
 66  Sexo (Desc)                     14279 non-null  int64
 67  GRD                             14279 non-null  int64
dtypes: float64(30), int64(3), object(35)
memory usage: 7.4+ MB

In [5]:
dataset_el_pino.isnull().sum()

Diag 01 Principal (cod+des)       0
Diag 02 Secundario (cod+des)      0
Diag 03 Secundario (cod+des)      0
Diag 04 Secundario (cod+des)      0
Diag 05 Secundario (cod+des)      0
                                 ..
Proced 29 Secundario (cod+des)    0
Proced 30 Secundario (cod+des)    0
Edad en años                      0
Sexo (Desc)                       0
GRD                               0
Length: 68, dtype: int64

# Label encoding

In [6]:
name_columns_for_label = dataset_el_pino.columns.tolist()

# I will delete age and sex in the columns of the dataset 
name_columns_for_label.remove('Edad en años')
name_columns_for_label.remove('Sexo (Desc)')

In [10]:
name_columns_for_label[2]

'Diag 03 Secundario (cod+des)'

In [8]:
label_encoding = LabelEncoder()
for col_name in name_columns_for_label:
    dataset_el_pino[col_name] = label_encoding.fit_transform(dataset_el_pino[col_name])

In [9]:
dataset_el_pino.head()

,Diag 01 Principal (cod+des),Diag 02 Secundario (cod+des),Diag 03 Secundario (cod+des),Diag 04 Secundario (cod+des),Diag 05 Secundario (cod+des),Diag 06 Secundario (cod+des),Diag 07 Secundario (cod+des),Diag 08 Secundario (cod+des),Diag 09 Secundario (cod+des),Diag 10 Secundario (cod+des),...,Proced 24 Secundario (cod+des),Proced 25 Secundario (cod+des),Proced 26 Secundario (cod+des),Proced 27 Secundario (cod+des),Proced 28 Secundario (cod+des),Proced 29 Secundario (cod+des),Proced 30 Secundario (cod+des),Edad en años,Sexo (Desc),GRD
0,24,41,373,638,38,462,391,26,6,242,...,112,19,40,40,41,39,13,40,1,135
1,1364,508,1016,889,796,833,693,297,260,244,...,57,42,53,40,39,73,39,53,1,14
2,575,1177,1051,452,975,330,649,23,31,9,...,112,54,44,99,22,26,26,65,1,14
3,622,670,711,120,169,149,321,411,251,411,...,18,1,3,90,90,82,86,61,1,15
4,1342,1571,1102,964,923,362,297,574,491,349,...,46,53,51,72,88,73,9,30,1,15

# Write new CSV

In [12]:
dataset_el_pino.to_csv("../data/dataModelCSV/label_encoding.csv", sep=';', index=False)